tag-name = "v{{version}}"
tag-message = "Release {{version}}"
pre-release-commit-message = "chore: release {{version}}"
sign-tag = false
sign-commit = false
publish = false
push = true
allow-branch = ["master"]
